# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-01-05 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('pulses_today', models.IntegerField()),
                ('pulses_total', models.IntegerField()),
            ],
        ),
    ]
