# Generated by Django 2.2.7 on 2019-11-26 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0002_auto_20190105_1553'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeekHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('week', models.IntegerField()),
                ('value', models.IntegerField()),
                ('counter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='counter.Counter')),
            ],
        ),
        migrations.CreateModel(
            name='DayHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('hour', models.IntegerField()),
                ('value', models.IntegerField()),
                ('counter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='counter.Counter')),
            ],
        ),
    ]
