# Generated by Django 2.2.7 on 2019-11-26 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0003_dayhistory_weekhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='counter',
            name='conversion_multiplier',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='counter',
            name='unit',
            field=models.CharField(choices=[('m3/h', 'kubiek'), ('kWh', 'kilowattuur')], default='m3/h', max_length=100),
        ),
    ]
