# Generated by Django 2.2.7 on 2019-12-30 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0004_auto_20191126_2315'),
    ]

    operations = [
        migrations.CreateModel(
            name='HourHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('hour', models.IntegerField()),
                ('value', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='counter',
            name='conversion_multiplier',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='weekhistory',
            name='date',
            field=models.DateField(),
        ),
        migrations.DeleteModel(
            name='DayHistory',
        ),
        migrations.AddField(
            model_name='hourhistory',
            name='counter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='counter.Counter'),
        ),
    ]
