# Generated by Django 2.2.7 on 2019-12-30 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0005_auto_20191230_2023'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WeekHistory',
            new_name='DayHistory',
        ),
    ]
