# Generated by Django 2.2.7 on 2019-12-30 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0006_auto_20191230_2026'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dayhistory',
            old_name='week',
            new_name='weekday',
        ),
    ]
